image: node:21-slim

build_stage:
  script:
    - RUN apt-get update
    - apt-get install python -y
    - pip install mkdocs mkdocs-material
    - mkdocs build --verbose
  artifacts:
    untracked: true
    paths:
      - site
  only:
    - main

deploy_stage:
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  dependencies:
    - build_stage
