stages:
  - build_stage
  - deploy_stage

build_stage:
  image: python:3.11
  script:
    - pip install mkdocs mkdocs-material
    - mkdocs build --verbose
  artifacts:
    paths:
      - site
  only:
    - main

deploy_stage:
  image: node:21-slim
  script:
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  dependencies:
    - build_stage
