image: python:3.11

before_script:
  - pip install mkdocs mkdocs-material

pages:
  script:
    - mkdocs build --verbose
  artifacts:
    paths:
      - site
  only:
    - main

deploy:
  script:
    - npm install -g firebase-tools
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - main
