site_name: My Docs

nav:
  - Home: index.md
  - Lehrplan:
    - Allgemein: lehrplan/lehrplan.md
    - Clean Code:
        - Für Lehrer: lehrplan/clean_code/clean-code-lehrer.md
        - Einführung: lehrplan/clean_code/einführung/Einführung.md
        - Best Practices: lehrplan/clean_code/best_practices/kamele_und_schlangen.md
  - Checkliste: lehrplan/checkliste.md
  - Begriffssammlung: lehrplan/begriffssammlung.md
  - Projekte:
      - Projekt 1 A: projekt/projekt1a.md
      - Projekt 1 B: projekt/projekt1b.md
      - Projekt 2 A: projekt/projekt2a.md
      - Projekt 2 B: projekt/projekt2b.md
      - Projekt 3 A: projekt/projekt3a.md
      - Projekt 3 B: projekt/projekt3b.md
  - Für Autoren:
      - Ansprechpartner: orga/ansprechpartner.md
      - Leitfaden: orga/leitfaden.md
      - Inhalte: orga/inhalte.md
      - Viktors ToDo's: orga/todo.md