site_name: Python Skript

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Lehrplan: lehrplan/lehrplan.md
  - Werkzeuge:
      - git: lehrplan/git/git.md
