site_name: My Docs

extra_css:
  - custom.css

nav:
  - Home: index.md
  - Lehrplan:
    - Allgemein: lehrplan/lehrplan.md
    - Clean Code:
        - Einführung: lehrplan/clean_code/Introduction.md
        - Grundlagen: lehrplan/clean_code/Basics.md
        - Schlechten Code erkennen: lehrplan/clean_code/DetectingBadCode.md
        - Besseren Code schreiben: lehrplan/clean_code/TheGoodPractices.md
        - Namenskonventionen: lehrplan/clean_code/Conventoons.md
        - Best Practices: lehrplan/clean_code/CamelsAndSnakes.md
        - DRY: lehrplan/clean_code/DRY.md
  - Checkliste: lehrplan/checkliste.md
  - Begriffssammlung: lehrplan/begriffssammlung.md
  - Projekte:
      - Projekt 1 A: projekt/projekt1a.md
      - Projekt 1 B: projekt/projekt1b.md
      - Projekt 2 A: projekt/projekt2a.md
      - Projekt 2 B: projekt/projekt2b.md
      - Projekt 3 A: projekt/projekt3a.md
      - Projekt 3 B: projekt/projekt3b.md
  - Für Autoren:
      - Ansprechpartner: orga/ansprechpartner.md
      - Leitfaden: orga/leitfaden.md
      - Inhalte: orga/inhalte.md
      - Viktors ToDo's: orga/todo.md