site_name: My Docs

nav:
  - Home: index.md
  - Lehrplan:
    - Allgemein: lehrplan/lehrplan.md
    - Clean Code:
        - Einführung: lehrplan/clean_code/Introduction.md
        - Grundlagen: lehrplan/clean_code/Basics.md
        - Besseren Code schreiben:
            - Globale Variable: lehrplan/clean_code/GlobaleParameter.md
            - Fehlerbehandlung: lehrplan/clean_code/Fehlerbehandlung.md
            - List Comprehension: lehrplan/clean_code/ListComprehension.md
            - Namenskonventionen: lehrplan/clean_code/Benennungskonventionen.md
            - Kommentare: lehrplan/clean_code/Kommentare.md
            - DRY: lehrplan/clean_code/DRY.md
            - Funktionsgestaltung: lehrplan/clean_code/Funktionsgestaltung.md
            - Funktionsparameter: lehrplan/clean_code/Typehints.md
            - Aufgaben: lehrplan/clean_code/Aufgaben.md
        - Anhang: lehrplan/clean_code/Anhang.md
  - Checkliste: lehrplan/checkliste.md
  - Begriffssammlung: lehrplan/begriffssammlung.md
  - Projekte:
      - Projekt 1 A: projekt/projekt1a.md
      - Projekt 1 B: projekt/projekt1b.md
      - Projekt 2 A: projekt/projekt2a.md
      - Projekt 2 B: projekt/projekt2b.md
      - Projekt 3 A: projekt/projekt3a.md
      - Projekt 3 B: projekt/projekt3b.md
  - Für Autoren:
      - Ansprechpartner: orga/ansprechpartner.md
      - Leitfaden: orga/leitfaden.md
      - Inhalte: orga/inhalte.md
      - Viktors ToDo's: orga/todo.md