site_name: Python Skript

nav:
  - Lehrplan: lehrplan/lehrplan.md
  - Werkzeuge:
      - git: lehrplan/git/git.md

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      kernel_name: python3
